dist: trusty

language: node_js

node_js:
  - '10'
  - '8'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

sudo: required

before_install:
  - sudo apt-get -qq update
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export NODE_ENV=development

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test

env:
  - TRAVIS=travis CXX=g++-4.8
